---
- name: Install Docker
  gather_facts: No
  hosts: elc
 
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
 
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
 
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
 
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
 
    - name: Add user yc-user to docker group
      user:
        name: yc-user
        groups: docker
        append: yes

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes

    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1

    - name: Download and run elk cluster docker-compose mode
      get_url:
        url: https://github.com/alexeirom/elkcluster_docker.git 
        dest: /home/yc-user/elk/part-2

    - name: run the service defined in elk docker-compose.yml
      docker_compose:
        project_src: /home/yc-user/elk/part2

